//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoshevoiControl7.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Koshevoi_SalonEntities1 : DbContext
    {
        public Koshevoi_SalonEntities1()
            : base("name=Koshevoi_SalonEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Material> Material { get; set; }
        public DbSet<Proizvoditel> Proizvoditel { get; set; }
        public DbSet<Sotrudnik> Sotrudnik { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Uchet> Uchet { get; set; }
    }
}
