//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoshevoiControl7.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvoditel
    {
        public Proizvoditel()
        {
            this.Material = new HashSet<Material>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Material> Material { get; set; }
    }
}
